### ISSUE TITLE
Importação de Solicitações Pendentes para item de referência

### ISSUE THREAD

**Issue by Alliny** [phiny/seslogos#10]
Quando a UBS Solicitar um item que ela não possui permissão de dispensar (quando ela não estiver vinculada à um item de "referência"), permitir a importação e identificar o item como cancelado no relatório com mensagem de alerta destacando "UBS não dispensadora" ou mensagem semelhante. O item cancelado deve não ser contemplado no consolidado.

**Comment by phiny** [comment]
Implementado.
