### ISSUE TITLE
Cadastro - Tipo de Saída

### ISSUE THREAD

**Issue by Alliny** [phiny/seslogos#18]
Na atualização do tipo de saída, caso se exclua todos os tipos é possível salvar a alteração sendo sinalizado " tipo de saída atualizado", mas o mesmo não atualiza pelo fato de não poder deixar o campo em branco.

Sugestão: Não permitir que salve a atualização e sinalizar através de mensagem que o campo não pode ficar em branco.

**Comment by phiny** [comment]
implementado.
