### ISSUE TITLE
Balanço

### ISSUE THREAD

**Issue by Alliny** [phiny/seslogos#21]
Na tentativa de registrar no campo de quantidade uma letra ou um numero negativo, a logos trava ou acusa como "Balanço salvo com sucesso", mas como o caractere não é um número, o balanço não é salvo.

Sugestão:não aceitar que seja salvado o registro de balanço com valores que não sejam números iguais e acima de zero e  numerais. Aparecer uma mensagem de alerta no momento de salvar solicitando a alteração do campo preenchido.

**Comment by phiny** [comment]
corrigido.
