### ISSUE TITLE
Balanço - Impressão

### ISSUE THREAD

**Issue by Alliny** [phiny/seslogos#22]
No relatório impresso do balanço não possui linhas.

Incluir linhas no relatório para facilitar a visualização na contagem.

**Comment by phiny** [comment]
Problema não identificado.

IE
![image](https://user-images.githubusercontent.com/1081945/45853286-bc415e00-bd1a-11e8-92c4-51c7ecdf7c0b.png)


Chrome
![image](https://user-images.githubusercontent.com/1081945/45853320-f1e64700-bd1a-11e8-9584-efb0b4dda55a.png)

Firefox
![image](https://user-images.githubusercontent.com/1081945/45853354-278b3000-bd1b-11e8-8a64-a97d22a606e2.png)
