### ISSUE TITLE
Solicitações Dispensadas - Estorno

### ISSUE THREAD

**Issue by Alliny** [phiny/seslogos#27]
Quando é realizado a exclusão da solicitação já dispensada, o valor não é estornado (Estoque atualizado)

**Comment by phiny** [comment]
Não identifiquei o problema... verificar se a exclusão não foi efetuada em "Solicitações Pendentes".

![image](https://user-images.githubusercontent.com/1081945/45853844-f06a4e00-bd1d-11e8-91f6-79ff819273e4.png)
