### ISSUE TITLE
Consolidado Mensal - Relatório

### ISSUE THREAD

**Issue by Alliny** [phiny/seslogos#36]
O relatório criado é a foto da tela, onde alguns números estão subtraídos.

![relatorio consolidado](https://user-images.githubusercontent.com/42447155/45840588-bbde9e00-bced-11e8-93ec-61b6a5a9ff17.png)

Sugestão: Não aparecer os itens rejeitados no relatório consolidado.

**Comment by phiny** [comment]
O problema é da impressora que está cortando a página. Sugestão: Mudar orientação para paisagem.

Obs: A conversão do relatório para PDF é efetuado pelo browser e do plugin que converte para PDF. 

O chrome faz a melhor conversão.

![image](https://user-images.githubusercontent.com/1081945/45854122-c3b73600-bd1f-11e8-8724-855b4a06de44.png)
