### ISSUE TITLE
Itens de Referência

### ISSUE THREAD

**Issue by Alliny** [phiny/seslogos#37]
O sistema acatou a importação da requisição da UBS Paranoa Parque para Sulfadiazina comprimido (Referência) e não acatou a importação do mesmo medicamento para a solicitação do Núcleo de Patologia.

Os dois setores não estão cadastrados como referência

![image](https://user-images.githubusercontent.com/42447155/45841045-06ace580-bcef-11e8-9465-a57f7fd57e2e.png)

![image](https://user-images.githubusercontent.com/42447155/45841075-15939800-bcef-11e8-8dfb-073817a5a76e.png)

**Comment by phiny** [comment]
A solicitação da UBS Paranoa Parque  já existia na base, foi importada em 11/08/2018, ou seja, antes de existir a funcionalidade de rejeição.

![image](https://user-images.githubusercontent.com/1081945/45855257-a2594880-bd25-11e8-98c5-f007299ee077.png)
